const myAaray=[0,1,2,3,4]
//console.log(myAaray[2])
//myAaray.push(6)
//console.log(myAaray)
//myAaray.unshift(8)
//console.log(myAaray)
//myAaray.shift()
//console.log(myAaray)
//console.log(myAaray.includes(19))
//console.log(myAaray.indexOf(9))
//const newArr=myAaray.join()
//console.log(newArr)
const myN1=myAaray.slice(1,3)
console.log(myN1)
console.log(myAaray)
const a=myAaray.splice(2,4)
console.log(a)
console.log(myAaray)
// in alice our original array does'nt change but in aplice our original array change